### ISSUE TITLE
Valgrind: Invalid read of size 1 in data-source-dos.c:419

### ISSUE THREAD

**Issue by genodeftest** [freeserf/freeserf#186]
On current freeserf git master I am getting valgrind errors in data-source-dos.c:419 to 422. This happens when starting the application before starting any game.

Valgrind:
```
==23019== Invalid read of size 1
==23019==    at 0x440EA5: sprite_dos_base_t::get_masked(sprite_t*) (data-source-dos.cc:422)
==23019==    by 0x41E22A: frame_t::draw_masked_sprite(int, int, unsigned int, unsigned int) (gfx.cc:257)
==23019==    by 0x41E888: viewport_t::draw_up_tile_col(unsigned int, int, int, int, frame_t*) (viewport.cc:180)
==23019==    by 0x423A67: viewport_t::get_tile_frame(unsigned int, int, int) (viewport.cc:330)
==23019==    by 0x423D2E: viewport_t::draw_landscape() (viewport.cc:385)
==23019==    by 0x423E3C: viewport_t::internal_draw() (viewport.cc:2257)
==23019==    by 0x426BCC: gui_object_t::draw(frame_t*) (gui.cc:85)
==23019==    by 0x426BEC: gui_object_t::draw(frame_t*) (gui.cc:89)
==23019==    by 0x4267D0: interface_t::handle_event(event_t const*) (interface.cc:932)
==23019==    by 0x44170B: event_loop_t::notify_handlers(event_t*) (event_loop.cc:62)
==23019==    by 0x4418E7: event_loop_t::notify_draw(frame_t*) (event_loop.cc:138)
==23019==    by 0x441B85: event_loop_sdl_t::run() (event_loop-sdl.cc:262)
==23019==  Address 0xf9ab1f3 is 3 bytes after a block of size 2,560 alloc'd
==23019==    at 0x4C299CB: operator new[](unsigned long) (vg_replace_malloc.c:423)
==23019==    by 0x440779: sprite_dos_base_t::sprite_dos_base_t(void*, unsigned long) (data-source-dos.cc:432)
==23019==    by 0x44079A: sprite_dos_solid_t::sprite_dos_solid_t(void*, unsigned long, color_dos_t*) (data-source-dos.cc:220)
==23019==    by 0x44087D: data_source_dos_t::get_sprite(unsigned int) (data-source-dos.cc:215)
==23019==    by 0x41E1DF: frame_t::draw_masked_sprite(int, int, unsigned int, unsigned int) (gfx.cc:244)
==23019==    by 0x41E888: viewport_t::draw_up_tile_col(unsigned int, int, int, int, frame_t*) (viewport.cc:180)
==23019==    by 0x423A67: viewport_t::get_tile_frame(unsigned int, int, int) (viewport.cc:330)
==23019==    by 0x423D2E: viewport_t::draw_landscape() (viewport.cc:385)
==23019==    by 0x423E3C: viewport_t::internal_draw() (viewport.cc:2257)
==23019==    by 0x426BCC: gui_object_t::draw(frame_t*) (gui.cc:85)
==23019==    by 0x426BEC: gui_object_t::draw(frame_t*) (gui.cc:89)
==23019==    by 0x4267D0: interface_t::handle_event(event_t const*) (interface.cc:932)
```

GDB:
```
Program received signal SIGTRAP, Trace/breakpoint trap.
-----------------------------------------------------------------------------------------------------------------------[regs]
  RAX: 0x0000000000000000  RBX: 0x000000000F9AB1F4  RCX: 0x0000000000000A00  RDX: 0x000000000F9ABDD0  o d i t s Z a P c 
  RSI: 0x0000000000000001  RDI: 0x000000000F9AB230  RBP: 0x000000000F9ABCA4  RSP: 0x0000000FFEFFFB70  RIP: 0x0000000000440EA5
  R8 : 0x0000000000000107  R9 : 0x00000000066B1984  R10: 0x0000000000000020  R11: 0x0000000000000060  R12: 0x000000000F9ABD60
  R13: 0x000000000F9AA780  R14: 0x000000000F9AC7D4  R15: 0x000000000F9AB1F0
  CS: 0000  DS: 0000  ES: 0000  FS: 0000  GS: 0000  SS: 0000				
-----------------------------------------------------------------------------------------------------------------------[code]
=> 0x440ea5 <sprite_dos_base_t::get_masked(sprite_t*)+245>:	movzx  eax,BYTE PTR [rbx-0x1]
   0x440ea9 <sprite_dos_base_t::get_masked(sprite_t*)+249>:	and    al,BYTE PTR [rbp-0x1]
   0x440eac <sprite_dos_base_t::get_masked(sprite_t*)+252>:	mov    BYTE PTR [r14-0x1],al
   0x440eb0 <sprite_dos_base_t::get_masked(sprite_t*)+256>:	mov    rax,QWORD PTR [r12]
   0x440eb4 <sprite_dos_base_t::get_masked(sprite_t*)+260>:	mov    rax,QWORD PTR [rax+0x18]
   0x440eb8 <sprite_dos_base_t::get_masked(sprite_t*)+264>:	cmp    rax,0x441150
   0x440ebe <sprite_dos_base_t::get_masked(sprite_t*)+270>:	je     0x440e60 <sprite_dos_base_t::get_masked(sprite_t*)+176>
   0x440ec0 <sprite_dos_base_t::get_masked(sprite_t*)+272>:	mov    QWORD PTR [rsp+0x8],rsi
-----------------------------------------------------------------------------------------------------------------------------
sprite_dos_base_t::get_masked (this=0xf9aa780, mask=<optimized out>) at src/data-source-dos.cc:422
422	      *pos++ = *s_pos++ & *m_pos++;
gdb$ bt
#0  sprite_dos_base_t::get_masked (this=0xf9aa780, mask=<optimized out>) at src/data-source-dos.cc:422
#1  0x000000000041e22b in frame_t::draw_masked_sprite (this=this@entry=0xf9a9460, x=x@entry=0xfffffff0, y=0x0, mask=mask@entry=0x5a, sprite=<optimized out>) at src/gfx.cc:257
#2  0x000000000041e644 in viewport_t::draw_triangle_up (this=this@entry=0xfcb71c0, x=x@entry=0xfffffff0, y=<optimized out>, m=m@entry=0x0, left=left@entry=0x1, right=right@entry=0x1, pos=0x860, frame=0xf9a9460) at src/viewport.cc:109
#3  0x000000000041e889 in viewport_t::draw_up_tile_col (this=this@entry=0xfcb71c0, pos=0x860, pos@entry=0x820, x_base=x_base@entry=0xfffffff0, y_base=y_base@entry=0x0, max_y=max_y@entry=0x140, frame=frame@entry=0xf9a9460) at src/viewport.cc:180
#4  0x0000000000423a68 in viewport_t::get_tile_frame (this=this@entry=0xfcb71c0, tid=tid@entry=0x9, tc=tc@entry=0x1, tr=tr@entry=0x2) at src/viewport.cc:330
#5  0x0000000000423d2f in viewport_t::draw_landscape (this=0xfcb71c0) at src/viewport.cc:385
#6  0x0000000000423e3d in viewport_t::internal_draw (this=0xfcb71c0) at src/viewport.cc:2257
#7  0x0000000000426bcd in gui_object_t::draw (this=0xfcb71c0, frame=0xfcc5cb0) at src/gui.cc:85
#8  0x0000000000426bed in gui_object_t::draw (this=0xf928090, frame=0xf9526d0) at src/gui.cc:89
#9  0x00000000004267d1 in interface_t::handle_event (this=<optimized out>, event=<optimized out>) at src/interface.cc:932
#10 0x000000000044170c in event_loop_t::notify_handlers (this=this@entry=0xf94fa60, event=event@entry=0xffefffe60) at src/event_loop.cc:62
#11 0x00000000004418e8 in event_loop_t::notify_draw (this=this@entry=0xf94fa60, frame=frame@entry=0xf9526d0) at src/event_loop.cc:138
#12 0x0000000000441b86 in event_loop_sdl_t::run (this=0xf94fa60) at src/event_loop-sdl.cc:262
#13 0x00000000004040fc in main (argc=<optimized out>, argv=<optimized out>) at src/freeserf.cc:285
```

**Comment by wdigger** [comment]
I have no valgrind right now.
Please check this fix https://github.com/wdigger/freeserf.git and if it's ok, I commit it.

**Comment by genodeftest** [comment]
These Valgrind errors are gone now. Looks fine to me (although I don't understand the code – I'm not a C++ programmer)
